services:
  mysql:
    image: mysql:8.0
    container_name: protegepet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    command: --collation-server=utf8mb4_unicode_ci
    volumes:
      - protege-pet-mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - protege-pet-network

  api:
    build: .
    container_name: protegepet-api
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - protege-pet-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: protege-pet-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    ports:
      - '8080:80'
    networks:
      - protege-pet-network

volumes:
  protege-pet-mysql-data:

networks:
  protege-pet-network:
